dT(Xtrain,Ytrain,features)
{
    base case - 1. pure node 
    //find all possible  classes in Y
    // if all the labels are of same class then pure
    if Length of set(Y)=1 means all values  are same means only 1 class is left
    //means  pure node
    2. feature len =0
    max_gain
    for every feature (f) calculate information gain
                 max_gain=max(max_gain,gain(X,Y,f))
    max_gain,final feature
    for all unique labels(rows) in finalfeature
    i.e set(x[:,finalfeature])
    call recursion dT(X,Y,features-final_features)
}
gain(X,Y , selected feature)
{
    set(X[:,SelectedFeature])
}

In [1]:
import numpy as np
#OR TABLE
or1=np.array([[True,True,True],[False,True,True],[True,False,True],[False,False,False]])
xtrain=or1[:,:-1]
ytrain=or1[:,-1]

f=xtrain.shape[1]

ytrain.shape
#print(xtrain.shape[0])


#Rough
split=or1[np.where(or1[:,0] == False)]
print(split)
or1


[[False  True  True]
 [False False False]]


array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False, False, False]], dtype=bool)

In [3]:
def  gain (or1,xtrain,ytrain,f):
    totaldp=xtrain.shape[0] #datapoints in parent node
    current_entropy=entropy(ytrain) #entropy of parent node
    lower_weighted_en=0 # childnodes' aggregate entropy
    
    #print(or1)
    for  i in set(xtrain[:,f]):
        currdp=(xtrain[:,f]==i).sum() #datapoints in current split of that feature for value i (of feature)
        split=or1[np.where(or1[:,f]==i)] #splitting the data on that value of feature
        xt=split[:,:-1]
        yt=split[:,-1]
       
        lower_weighted_en=lower_weighted_en+(entropy(yt)*currdp)/totaldp #Adding entropies of all i to form aggregate
        #print("LOWER:::",lower_weighted_en,"currdp:",currdp,"total:",totaldp)
    return current_entropy-lower_weighted_en #returing info gain   
        


In [16]:
def dT(or1,xtrain,ytrain,f,level):
    
    print()
    level=level+1
    print("Level ",level)
    count(ytrain)
    print("Current Entropy is = ",entropy(ytrain))
    
    #base case
    if (f==0 or len(set(ytrain))==1):
        print("Reached leaf  Node")
        return
    
    
    max_gain=-10000
    final_feature=12
    for i in range (f): #for every feature
        currgain=gain(or1,xtrain,ytrain,i) #gain on feature f
        #print("GAIN::::",currgain)
    
        if (max_gain<currgain):
            max_gain=currgain
            final_feature=i
            
    print("Splitting on feature",final_feature,"with gain ratio ",max_gain)
    
    #Callinng on every value of selected feature 
    for  i in set(or1[:,final_feature]):
        split=or1[np.where(or1[:,final_feature]==i)]
        #print(split)
        #REMOVING final_feature before recurring
        a=split[:,:final_feature]
        b=split[:,final_feature+1:-1]
        xt=np.concatenate((a, b), 1)
        yt=split[:,-1]
        c=split[:,final_feature+1:]
        split=np.concatenate((a,c),1) #Removing from whole set as well
        dT(split,xt,yt,f-1,level) #calling on dT with decrement in feature value
        


In [17]:
def count(ytrain):
    for  i in set(ytrain):
        c=(ytrain==i).sum()
        print("Count  of ", i,"=",c)
        

In [18]:
import math as m
def entropy(ytrain):
    totaldp=ytrain.shape[0]
    info=0
    for i in set(ytrain): #for every distinct class
        currcount=(ytrain==i).sum() #current class count dp(datapoints)
        info=info-((currcount/totaldp)*m.log((currcount/totaldp),2)) # aggregating for all the classes (all i s)
    return info

In [19]:
dT(or1,xtrain,ytrain,f,-1)


Level  0
Count  of  False = 1
Count  of  True = 3
Current Entropy is =  0.811278124459
Splitting on feature 0 with gain ratio  0.311278124459

Level  1
Count  of  False = 1
Count  of  True = 1
Current Entropy is =  1.0
Splitting on feature 0 with gain ratio  1.0

Level  2
Count  of  False = 1
Current Entropy is =  0.0
Reached leaf  Node

Level  2
Count  of  True = 1
Current Entropy is =  0.0
Reached leaf  Node

Level  1
Count  of  True = 2
Current Entropy is =  0.0
Reached leaf  Node


In [288]:
#AT level 1 it is  showing split on feature 0 but its actually on 1 only
#after the split and removal of f0 ,f1 becomes  f0.
#Rough
split=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(split)
a=split[:,:1]
b=split[:,2:-1]
xt=np.concatenate((a, b), 1)
print(xt)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[1 3]
 [4 6]
 [7 9]]
