In [72]:
import numpy as np

In [73]:
def fit(x_train,y_train):
    result={}
    classes=set(y_train)
    result['total_data']=len(y_train)

    for current_class in classes:
        result[current_class]={}
        current_class_rows=(current_class==y_train)
        x_train_current=x_train[current_class_rows]
        y_train_current=y_train[current_class_rows]
        num_features=x_train.shape[1]
        result[current_class]['total_count']=len(y_train_current)
        
        for j in range(num_features):
            result[current_class][j]={}
            all_possible_values=set(x_train[:,j])
            
            for current_value in all_possible_values:
                result[current_class][j][current_value]=(x_train_current[:,j]==current_value).sum()
                
    return result

In [74]:
def probability(dictionary,x,current_class):
   # print(current_class)
    output=np.log(dictionary[current_class]['total_count'])-np.log(dictionary['total_data'])
    num_features=len(dictionary[current_class].keys())-1
    for j in range(num_features):
        xj=x[j]
        count_current_class_with_value_xj=dictionary[current_class][j][xj] +1
        count_current_class=dictionary[current_class]['total_count'] +len(dictionary[current_class][j].keys())
        current_probability=np.log(count_current_class_with_value_xj)-np.log(count_current_class)
        output+=current_probability
        
    return output

In [75]:
def predictSinglePoint(dictionary,x):
    classes=dictionary.keys()
    best_p=-1000
    best_class=-1000
    fr=True
    for current_class in classes:
        if(current_class=='total_data'):
            continue
            
        p=probability(dictionary,x,current_class)
       # print(p)
        if(fr or p>best_p):
            best_p=p
            best_class=current_class
        fr=False
        
    return best_class
        

In [76]:
def predict(dictionary,x_test):
    ypred=[]
    for x in x_test:
        x_class=predictSinglePoint(dictionary,x)
        ypred.append(x_class)
        
    return ypred

In [77]:
def makelabelled(column):
    secondlimit=column.mean()
    firstlimit=0.5*secondlimit
    thirdlimit=1.5*secondlimit
    for i in range(len(column)):
        if(column[i]<firstlimit):
            column[i]=0
        elif(column[i]<secondlimit):
            column[i]=1
        elif(column[i]<thirdlimit):
            column[i]=2
        else:
            column[i]=3
    return column

In [78]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix


In [79]:
iris=datasets.load_iris()
x=iris.data
y=iris.target
print(x)
print(y)

for i in range(x.shape[1]):
    x[:,i]=makelabelled(x[:,i])
    
print(x)

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=0)
dictionary=fit(xtrain,ytrain)
print(dictionary)

predictions=predict(dictionary,xtest)

print(confusion_matrix(ytest,predictions))
print(classification_report(ytest,predictions))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [81]:
np.log(dictionary[1]["total_count"])

3.5263605246161616

In [82]:
np.log(dictionary['total_data'])

4.718498871295094