# V3 has implementation of naive bayes from scratch
# we use previously stored dictionary, training and testing data for 
# fast accessing and apply our multinomial naive bayes
# the predict function is the only one which takes time (as it computes 2000 iterations

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('opfile2.csv') # read training and testing data
dftest=pd.read_csv('testing_data_frame.csv')

In [3]:
df.shape

(19997, 1002)

In [4]:
dftest.shape

(2000, 1002)

In [5]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split

In [6]:
dictionary={}
fp=open('final_vocab_file2','r+')
l=fp.readlines()
l

["('cmu', 52409)\n",
 "('news', 34309)\n",
 "('srv', 32359)\n",
 "('cantaloupe', 26048)\n",
 "('net', 25459)\n",
 "('message', 21954)\n",
 "('subject', 21589)\n",
 "('lines', 20894)\n",
 "('date', 20787)\n",
 "('apr', 20510)\n",
 "('newsgroups', 20404)\n",
 "('path', 20369)\n",
 "('organization', 19840)\n",
 "('state', 18842)\n",
 "('gmt', 17773)\n",
 "('ohio', 15887)\n",
 "('writes', 14686)\n",
 "('article', 13435)\n",
 "('comp', 13101)\n",
 "('references', 12981)\n",
 "('talk', 12308)\n",
 "('misc', 11892)\n",
 "('ans', 11076)\n",
 "('sender', 11040)\n",
 "('howland', 10981)\n",
 "('reston', 10946)\n",
 "('don', 10640)\n",
 "('people', 10364)\n",
 "('university', 9958)\n",
 "('posting', 9793)\n",
 "('nntp', 9377)\n",
 "('mps', 9206)\n",
 "('host', 8934)\n",
 "('sci', 8756)\n",
 "('usenet', 8308)\n",
 "('zaphod', 8302)\n",
 "('alt', 7924)\n",
 "('politics', 7869)\n",
 "('windows', 7584)\n",
 "('time', 7073)\n",
 "('rutgers', 7014)\n",
 "('harvard', 6923)\n",
 "('eng', 6883)\n",
 "('re

In [7]:
import string

In [8]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [9]:
# read dictionary from file made and putting it in a dictionary

In [10]:
key=""
value=-1
for s in l:
    ts=s.strip().split(',')
    for i in ts:
        #print(i)
        templist=[letter for letter in i if letter not in string.punctuation]
        tempstring=''.join(templist).strip()
        if(tempstring.isalpha()):
            dictionary[tempstring]=value
            key=tempstring
        elif(tempstring.isnumeric()):
            dictionary[key]=int(tempstring)
            
        
        #print(tempstring)
        #print(tempstring.isalpha(),tempstring.isnumeric())
    #tup=tuple(ts)
    #print(ts)
len(dictionary)

1000

In [11]:
dictionary

{'cmu': 52409,
 'news': 34309,
 'srv': 32359,
 'cantaloupe': 26048,
 'net': 25459,
 'message': 21954,
 'subject': 21589,
 'lines': 20894,
 'date': 20787,
 'apr': 20510,
 'newsgroups': 20404,
 'path': 20369,
 'organization': 19840,
 'state': 18842,
 'gmt': 17773,
 'ohio': 15887,
 'writes': 14686,
 'article': 13435,
 'comp': 13101,
 'references': 12981,
 'talk': 12308,
 'misc': 11892,
 'ans': 11076,
 'sender': 11040,
 'howland': 10981,
 'reston': 10946,
 'don': 10640,
 'people': 10364,
 'university': 9958,
 'posting': 9793,
 'nntp': 9377,
 'mps': 9206,
 'host': 8934,
 'sci': 8756,
 'usenet': 8308,
 'zaphod': 8302,
 'alt': 7924,
 'politics': 7869,
 'windows': 7584,
 'time': 7073,
 'rutgers': 7014,
 'harvard': 6923,
 'eng': 6883,
 'rec': 6453,
 'good': 6308,
 'system': 6267,
 'crabapple': 6235,
 'sei': 6201,
 'noc': 6191,
 'soc': 6168,
 'das': 6068,
 'xref': 6064,
 'cis': 5752,
 'europa': 5448,
 'gtefsd': 5429,
 'ece': 5396,
 'uunet': 5369,
 'god': 5366,
 'world': 5354,
 'religion': 5351,


In [12]:
import os
import re

In [13]:
ls=os.listdir('./mini_newsgroups/')
ls

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [14]:
fsw=open('stopwords_en.txt','r')
stop_words=fsw.read().split('\n')
print(len(stop_words))
stop_words

571


['a',
 "a's",
 'able',
 'about',
 'above',
 'according',
 'accordingly',
 'across',
 'actually',
 'after',
 'afterwards',
 'again',
 'against',
 "ain't",
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'apart',
 'appear',
 'appreciate',
 'appropriate',
 'are',
 "aren't",
 'around',
 'as',
 'aside',
 'ask',
 'asking',
 'associated',
 'at',
 'available',
 'away',
 'awfully',
 'b',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'both',
 'brief',
 'but',
 'by',
 'c',
 "c'mon",
 "c's",
 'came',
 'can',
 "can't",
 'cannot',
 'cant',
 'cause',
 'causes',
 'certain',
 'certainly',
 'changes',
 'clearly',
 'co',
 'com',
 'come',
 'c

In [15]:
df.head()

Unnamed: 0  cmu  news  srv  cantaloupe  net  message  subject  lines  date  \
0           0    5     4    3           2    2        1        1      2     1   
1           1    4     3    3           2    1        2        2      1     1   
2           2    3     2    2           1    1        1        1      1     2   
3           3    4     1    3           2    1        1        1      1     1   
4           4    4     0    3           2    1        1        1      1     1   

      ...       saimiri  citizens  ken  allowed  americans  age  asd  suppose  \
0     ...             0         0    0        0          3    0    0        0   
1     ...             0         1    0        0          0    0    0        0   
2     ...             0         0    0        0          0    1    0        0   
3     ...             0         0    0        0          0    0    0        0   
4     ...             0         0    0        0          0    0    0        0   

   imagine       target  
0        0  alt.atheism  
1        1  alt.atheism  
2        0  alt.atheism  
3        0  alt.atheism  
4        0  alt.atheism  

[5 rows x 1002 columns]

In [16]:
dftest.head()

Unnamed: 0  cmu  news  srv  cantaloupe  net  message  subject  lines  date  \
0           0    4     0    3           2    1        1        1      1     1   
1           1    3     1    2           1    2        1        1      1     1   
2           2    3     1    2           1    2        1        1      1     1   
3           3    3     0    2           1    1        1        1      1     1   
4           4    1     3    1           1    1        1        1      1     1   

      ...       saimiri  citizens  ken  allowed  americans  age  asd  suppose  \
0     ...             0         0    0        0          0    0    0        0   
1     ...             0         0    0        0          0    0    0        0   
2     ...             0         0    0        0          0    0    1        0   
3     ...             0         0    0        0          0    0    1        0   
4     ...             0         0    0        0          0    0    0        0   

   imagine       target  
0        0  alt.atheism  
1        0  alt.atheism  
2        0  alt.atheism  
3        0  alt.atheism  
4        0  alt.atheism  

[5 rows x 1002 columns]

In [17]:
del df['Unnamed: 0']
del dftest['Unnamed: 0']

In [18]:
print(df.head())
print(dftest.head())

   cmu  news  srv  cantaloupe  net  message  subject  lines  date  apr  \
0    5     4    3           2    2        1        1      2     1    1   
1    4     3    3           2    1        2        2      1     1    1   
2    3     2    2           1    1        1        1      1     2    1   
3    4     1    3           2    1        1        1      1     1    1   
4    4     0    3           2    1        1        1      1     1    1   

      ...       saimiri  citizens  ken  allowed  americans  age  asd  suppose  \
0     ...             0         0    0        0          3    0    0        0   
1     ...             0         1    0        0          0    0    0        0   
2     ...             0         0    0        0          0    1    0        0   
3     ...             0         0    0        0          0    0    0        0   
4     ...             0         0    0        0          0    0    0        0   

   imagine       target  
0        0  alt.atheism  
1        1  alt.

In [19]:
XTRAIN=df.iloc[:,:df.shape[1]-1]
YTRAIN=df.iloc[:,-1]

XTest=dftest.iloc[:,:dftest.shape[1]-1]
YTest=dftest.iloc[:,-1]

In [20]:
print(XTRAIN.shape)
print(YTRAIN.shape)
print(XTest.shape)
print(YTest.shape)

(19997, 1000)
(19997,)
(2000, 1000)
(2000,)


In [21]:
XTRAIN2,XTest2,YTRAIN2,YTest2=train_test_split(XTRAIN,YTRAIN)

XTest_mini=dftest.iloc[:,:dftest.shape[1]-1]
YTest_mini=dftest.iloc[:,-1]

In [22]:
print(XTRAIN2.shape)
print(YTRAIN2.shape)
print(XTest_mini.shape)
print(YTest_mini.shape)

(14997, 1000)
(14997,)
(2000, 1000)
(2000,)


# NOW APPLYING SELF MADE MULTINOMIAL NAIVE BAYES ALGO

In [23]:
no_of_words=len(dictionary)
no_of_words

1000

In [24]:
# fit makes a dict which has keys as classes and value as another dict, dict 2

# dict2 has keys as words (features) and values as its freq in each class 

In [25]:
def fit(x_train,y_train):
    result={}
    classes=set(y_train)
    #result['total_docs']=len(classes)
    result['total_docs']=x_train.shape[0]

    for current_class in classes:
        result[current_class]={}
        current_class_rows=(current_class==y_train)
        x_train_current=x_train[current_class_rows]
        y_train_current=y_train[current_class_rows]     
        result[current_class]['no_of_docs']=x_train_current.shape[0]
        num_features=x_train_current.shape[1]
        total_words_in_current_class=0
        #freq_of_a_word_in_current_class=0
        for j in range(num_features):
            freq_of_a_word_in_current_class=x_train_current.iloc[:,j].sum()
            result[current_class][j]=freq_of_a_word_in_current_class
            total_words_in_current_class+=freq_of_a_word_in_current_class
            
        result[current_class]['total_words_in_class']=total_words_in_current_class
    return result 

In [26]:
XTRAIN2[('alt.atheism'==YTRAIN2)].shape[1]

1000

In [27]:
dictionary_count=fit(XTRAIN2,YTRAIN2)
print(dictionary_count)

{'total_docs': 14997, 'sci.space': {'no_of_docs': 762, 0: 2140, 1: 1381, 2: 1253, 3: 1042, 4: 1289, 5: 832, 6: 828, 7: 791, 8: 825, 9: 735, 10: 771, 11: 771, 12: 786, 13: 588, 14: 640, 15: 526, 16: 597, 17: 525, 18: 8, 19: 596, 20: 168, 21: 214, 22: 395, 23: 408, 24: 385, 25: 411, 26: 343, 27: 240, 28: 317, 29: 418, 30: 399, 31: 328, 32: 363, 33: 2099, 34: 265, 35: 292, 36: 141, 37: 93, 38: 6, 39: 308, 40: 6, 41: 262, 42: 287, 43: 92, 44: 185, 45: 389, 46: 212, 47: 222, 48: 223, 49: 8, 50: 226, 51: 279, 52: 179, 53: 164, 54: 156, 55: 230, 56: 187, 57: 19, 58: 261, 59: 2, 60: 227, 61: 196, 62: 2, 63: 834, 64: 232, 65: 38, 66: 231, 67: 171, 68: 2831, 69: 180, 70: 112, 71: 188, 72: 170, 73: 113, 74: 179, 75: 124, 76: 207, 77: 197, 78: 9, 79: 1, 80: 260, 81: 197, 82: 1181, 83: 113, 84: 95, 85: 156, 86: 24, 87: 53, 88: 166, 89: 35, 90: 41, 91: 110, 92: 227, 93: 82, 94: 181, 95: 132, 96: 111, 97: 15, 98: 216, 99: 91, 100: 148, 101: 83, 102: 171, 103: 77, 104: 101, 105: 252, 106: 198, 107: 12

In [28]:
dictionary_count.keys()

dict_keys(['total_docs', 'sci.space', 'talk.religion.misc', 'misc.forsale', 'rec.sport.baseball', 'comp.sys.mac.hardware', 'sci.crypt', 'rec.sport.hockey', 'comp.sys.ibm.pc.hardware', 'sci.electronics', 'comp.os.ms-windows.misc', 'talk.politics.mideast', 'rec.autos', 'talk.politics.misc', 'alt.atheism', 'soc.religion.christian', 'talk.politics.guns', 'rec.motorcycles', 'comp.windows.x', 'comp.graphics', 'sci.med'])

In [29]:
len(dictionary_count['comp.graphics'].keys())-2

1000

In [30]:
len(dictionary_count.keys())

21

In [31]:
# var names in following are taken so as to be self explanatory

# and log operations are taken because probability values can be very small to deal with
# so instead of multiplying those small values we would rather add them so as to prevent making them even smaller

In [32]:
def probability(dictionary_count,x,current_class):
    #p_y_equals_c=dictionary_count[current_class]['no_of_docs']/dictionary_count.keys()
    p_y_equals_c=np.log(dictionary_count[current_class]['no_of_docs'])-np.log(dictionary_count['total_docs'])

    #p_wi_in_doc=dictionary=1
    p_wi_in_doc=dictionary=0
    rangeloop=len(dictionary_count[current_class].keys())-2
    for i in range(rangeloop):
        wi=x[i]
        if(wi==0):
            probrv=0
        else:
            num=(dictionary_count[current_class][i] + 1)
            den=dictionary_count[current_class]['total_words_in_class'] + rangeloop
        #probrv=num/den
            probrv=np.log(num)-np.log(den)
        
        #p_wi_in_doc*=probrv
        p_wi_in_doc+=probrv
        
    #return p_wi_in_doc*p_y_equals_c
    return p_wi_in_doc+p_y_equals_c


In [33]:
def predictSinglePoint(dictionary_count,x):
    classes=dictionary_count.keys()
    best_p=-1000
    best_class=''
    fr=True
    for current_class in classes:
        if(current_class=='total_docs'):
            continue
        p=probability(dictionary_count,x,current_class)
        if(fr or p>best_p):
            best_p=p
            best_class=current_class
        fr=False
        
    return best_class

In [34]:
XTest_mini.shape[0]
#XTest_mini.iloc[0]

2000

In [35]:
def predict(dictionary_count,x_test_data):
    ypredrv=[]
    for i in range(x_test_data.shape[0]):
        print(i)
        x=x_test_data.iloc[i]
        x_class=predictSinglePoint(dictionary_count,x)
        ypredrv.append(x_class)
    return ypredrv

In [36]:
pred3=predict(dictionary_count,XTest_mini)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999


In [37]:
print(accuracy_score(YTest_mini,pred3))
print(confusion_matrix(YTest_mini,pred3))
print(classification_report(YTest_mini,pred3))

0.881
[[88  0  0  0  0  0  0  1  0  0  0  0  0  1  1  1  0  0  0  8]
 [ 0 78  3  5  3  6  0  0  1  1  0  0  3  0  0  0  0  0  0  0]
 [ 0  2 76 11  0  6  2  0  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  1  0 90  7  0  1  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  2 96  0  1  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  6  3  3  2 82  0  0  0  0  0  0  3  1  0  0  0  0  0  0]
 [ 0  0  0  0  2  0 96  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1 96  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0 98  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 98  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  3 96  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 95  4  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0 97  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  1  0  0  0  2 95  0  0  0  0  1  0]
 [ 0  0  0  0  0  2  0  1  0  0  0  0 11  1 85  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0 99