In [106]:
from sklearn import model_selection
import numpy as np


In [107]:
train_data=np.loadtxt('train.csv',delimiter=",")
test_data=np.loadtxt('test.csv',delimiter=",")



print(train_data[0])
print(np.mean(train_data,axis=0))

[   8.58   38.38 1021.03   84.37  482.26]
[  19.62971154   54.28815357 1013.26303233   73.275818    454.4312932 ]


In [108]:
arr = np.concatenate((train_data[:,0:(len(train_data[0])-1)], test_data),axis=0)


In [109]:
train = arr[0:len(train_data),:]
test = arr[len(train_data):,:]
N=len(train)
M=len(train[0])
train[0]
test[0]

array([  11.95,   42.03, 1017.58,   90.89])

In [110]:
def step_gradient(points,learning_rate,m,c):
    m_slope=np.zeros(M-1)
    c_slope=0
    for i in range(N):
        y=points[i,M-1]
        for j in range(M-1):
            x=points[i,j]
            m_slope[j]+=(-2/N)*(y-m[j]*x-c)*x
            c_slope+=(-2/N)*(y-m[j]*x-c)
    m_new=m-learning_rate*m_slope
    c_new=c-learning_rate*c_slope
 
    return m_new,c_new

In [111]:
def gd(points,learning_rate,num_iteration):
    m=np.zeros(M-1)
    c=0
    for i in range(num_iteration):
        m,c=step_gradient(points,learning_rate, m,c)
       
    return m,c
    

In [162]:
def run():
    
    learning_rate=0.000003
    num_iteration = 55
    m,c= gd(train,learning_rate,num_iteration)
    
    return m,c


In [163]:
def score(yp,yt):
    u=((yt-yp)**2).sum()
    v=((yt-yt.mean())**2).sum()
    score=1-(u/v)
    return score
train[:,M-1]

array([84.37, 66.74, 78.76, ..., 64.74, 63.63, 47.96])

In [164]:
m,c = run()
print(m,c)

[2.15233488e+30 5.96803997e+30 1.14026431e+38] 1.1253021122833853e+35


In [165]:

yp=np.zeros(len(test_data))
yp_train=np.zeros(len(train))
#yp_test=np.zeros(len(test))
"""for i in range(len(train)):
    for j in range(M-1):
        yp_train[i]+=(m[j]*train[i,j])
    yp_train[i]+=c
for i in range(len(test)):
    for j in range(M-1):
        yp_test[i]+=(m[j]*test[i,j])
    yp_test[i]+=c"""
for i in range(len(test)):
    for j in range(M-1):
        yp[i]+=(m[j]*test[i,j])
    yp[i]+=c
yp

array([1.16031129e+41, 1.15471259e+41, 1.14669654e+41, ...,
       1.15063045e+41, 1.15618353e+41, 1.16188485e+41])

In [166]:
np.savetxt("pred2.csv", yp, delimiter=",")